name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # Step 4: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t cogniform .

      # Step 5: Run Docker container locally
      - name: Run Docker container
        run: |
          docker stop cogniform || true
          docker rm cogniform || true
          docker run -d -p 8000:8000 --name cogniform cogniform