name: CD

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Install Docker
      - name: Install Docker
        run: |
          sudo apt-get update
          sudo apt-get remove -y docker docker-engine docker.io containerd runc || true
          curl -fsSL https://get.docker.com -o get-docker.sh
          sudo sh get-docker.sh

      # Step 3: Build Docker image
      - name: Build Docker image
        run: |
          docker build -t cogniform .

      # Step 4: Run Docker container locally
      - name: Run Docker container
        run: |
          docker stop cogniform || true
          docker rm cogniform || true
          docker run -d -p 8000:8000 --name cogniform cogniform