name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12.2'

      # Step 3: Install dependencies (including dev dependencies)
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install poetry
          poetry install

      # Step 4: Verify installed dependencies
      - name: List installed packages
        run: |
          poetry show

      # Step 5: Run tests
      - name: Run tests
        run: |
          poetry run pytest tests/

      # Step 6: Lint the code
      - name: Lint code
        run: |
          poetry run flake8 app tests

      # Step 7: Check code formatting
      - name: Check code formatting
        run: |
          poetry run black --check .